import "server-only";

// pricing_knobs の表示名・単位・説明文・公開可否（admin の Pricing タブと API 用）。値そのものは
// knobDefaults.ts の DEFAULT_KNOBS が SSOT。文字列に GPU 型番や原価の話が入るので、ブラウザへ配られる
// knobDefaults.ts から分けてある（2026-10-01、CLAUDE.md §2）。
import { DEFAULT_KNOBS, type KnobCategory, type KnobKey } from "@/lib/pricing/knobDefaults";

type KnobMeta = {
  value: number;
  label: string;
  category: KnobCategory;
  unit: string;
  description: string;
  /** Exposed to the browser via GET /api/studio/pricing. */
  isPublic: boolean;
};

const KNOB_TEXT: Record<KnobKey, Omit<KnobMeta, "value">> = {
  image_generate: {
    label: "画像生成",
    category: "feature_credits",
    unit: "C",
    description: "（廃止・未使用）旧 /api/generate（RunPod 画像生成）の単価。2026-10-01 に route ごと削除。DB 行は残置",
    isPublic: true,
  },
  angle_turbo_per_angle: {
    label: "Multi-Angle Turbo（廃止・未使用）",
    category: "feature_credits",
    unit: "C/構図",
    description: "（廃止）turbo/pro 統合前の名残。課金は angle_pro_per_angle を使用。",
    isPublic: false,
  },
  angle_pro_per_angle: {
    label: "Multi-Angle（1構図）",
    category: "feature_credits",
    unit: "C/構図",
    description: "1構図あたりの消費クレジット（40ステップ / 最低3構図）",
    isPublic: true,
  },
  angle_ref_multiplier_per_sub: {
    label: "Multi-Angle サブ参照 加算係数",
    category: "feature_credits",
    unit: "×/枚",
    description: "サブ参照1枚ごとに 1構図単価へ乗せる係数（係数 = 1 + これ×枚数）。0で無料。",
    isPublic: true,
  },
  angle_priority_parallel_rate: {
    label: "Multi-Angle 並列実行 上乗せ率",
    category: "feature_credits",
    unit: "×",
    description: "並列実行時に通常料金へ掛けて上乗せする割合（1.0 = 通常料金と同額を追加 = 合計 2 倍）。固定分と合算。",
    isPublic: true,
  },
  angle_priority_parallel_surcharge: {
    label: "Multi-Angle 並列実行 固定追加料金",
    category: "feature_credits",
    unit: "C",
    description: "並列実行時に 1 ジョブへ一律で足す固定分。率（angle_priority_parallel_rate）と合算。0 で比例分のみ。",
    isPublic: true,
  },
  cinematic_speed: {
    label: "Cinematic Speed Mode",
    category: "feature_credits",
    unit: "C",
    description: "1本あたりの消費クレジット（4ステップ / 512px）",
    isPublic: true,
  },
  cinematic_standard: {
    label: "Cinematic Standard Mode",
    category: "feature_credits",
    unit: "C",
    description: "1本あたりの消費クレジット（4ステップ / 768px）",
    isPublic: true,
  },
  cinematic_cinema_master: {
    label: "Cinematic Cinema Master",
    category: "feature_credits",
    unit: "C",
    description: "1本あたりの消費クレジット（20ステップ / 1024px）",
    isPublic: true,
  },
  director_per_second_fast: {
    label: "Cinematic Director Fast（秒あたり）",
    category: "feature_credits",
    unit: "C/秒",
    description: "Fastモード（8step蒸留・無音）の合計尺1秒あたり消費クレジット",
    isPublic: true,
  },
  director_per_second_quality: {
    label: "Cinematic Director Quality（秒あたり）",
    category: "feature_credits",
    unit: "C/秒",
    description: "Qualityモード（50step非蒸留・音声あり）の合計尺1秒あたり消費クレジット",
    isPublic: true,
  },
  director_min_credits: {
    label: "Cinematic Director 最低課金",
    category: "feature_credits",
    unit: "C",
    description: "1本あたりの最低消費クレジット（秒課金の下限）",
    isPublic: true,
  },
  director_priority_parallel_rate: {
    label: "Cinematic Director 並列実行 上乗せ率",
    category: "feature_credits",
    unit: "×",
    description: "並列実行時に通常料金へ掛けて上乗せする割合（1.0 = 通常料金と同額を追加 = 合計 2 倍）。固定分と合算。",
    isPublic: true,
  },
  director_priority_parallel_surcharge: {
    label: "Cinematic Director 並列実行 固定追加料金",
    category: "feature_credits",
    unit: "C",
    description: "並列実行時に 1 ジョブへ一律で足す固定分（コールドスタート分）。率と合算。",
    isPublic: true,
  },
  lora_caption_base: {
    label: "LoRA キャプション（1 回の基本料）",
    category: "feature_credits",
    unit: "C",
    description: "LoRA に最適化したキャプション作成の 1 回あたりの基本料（起動・読み込み分）",
    isPublic: true,
  },
  lora_caption_per_image: {
    label: "LoRA キャプション（1 枚あたり）",
    category: "feature_credits",
    unit: "C/枚",
    description: "LoRA に最適化したキャプション作成の 1 枚あたりの加算",
    isPublic: true,
  },
  director_extra_ref_rate: {
    label: "Cinematic Director 参照写真の追加 上乗せ率",
    category: "feature_credits",
    unit: "×/枚",
    description: "「顔写真として使う」で 2 枚目以降の写真 1 枚ごとに、動画の料金へ掛けて上乗せする割合（0.04 = 1 枚 4%、8 枚で 32%）。",
    isPublic: true,
  },
  director_ref_video_rate: {
    label: "Cinematic Director 参照動画 上乗せ率",
    category: "feature_credits",
    unit: "×",
    description: "動き・カメラの手本の動画を入れたときの上乗せ。通常料金 × ((1 + 参照秒/出力秒)² − 1) × この値（1.0 = 計算量の増え方そのまま。20 秒＋参照 10 秒で +125%）。",
    isPublic: true,
  },
  photo_director_base_credits: {
    label: "Photo Director 1 回の基本料",
    category: "feature_credits",
    unit: "C",
    description: "1 回ごとの固定分（GPU の起動・参照写真の読み込み）。合計 = これ + 1 枚ごと × 枚数（＋追加の参照写真の上乗せ）。",
    isPublic: true,
  },
  photo_director_per_image_credits: {
    label: "Photo Director 1 枚ごと",
    category: "feature_credits",
    unit: "C/枚",
    description: "1 回で出す枚数（4・6・8 枚。最低 4 枚）1 枚ごとの料金。",
    isPublic: true,
  },
  director_unrestricted_script_credits: {
    label: "Director / Photo 制限なしモード",
    category: "feature_credits",
    unit: "C",
    description: "台本・英訳・写真の指示文を、表現の制限のない AI（GPU 上）で書くときの追加料金。断られたときの「制限を解除」と、最初から選んだときの両方。",
    isPublic: true,
  },
  director_qwen_script_credits: {
    label: "Cinematic Director Advanced（Qwen台本生成）",
    category: "feature_credits",
    unit: "C",
    description: "Advancedモード（Qwenによる台本自動生成）使用時の追加消費クレジット",
    isPublic: true,
  },
  upscale_per_mp: {
    label: "超解像（100万画素あたり）",
    category: "feature_credits",
    unit: "C/MP",
    description: "出力の100万画素あたりの消費クレジット（× モデル係数）",
    isPublic: true,
  },
  upscale_min_credits: {
    label: "超解像 最低クレジット",
    category: "feature_credits",
    unit: "C",
    description: "1枚あたりの消費クレジット下限（コールドスタート償却）",
    isPublic: true,
  },
  lora_priority_parallel_rate: {
    label: "LoRA 並列実行 上乗せ率",
    category: "feature_credits",
    unit: "×",
    description: "学習中にもう 1 本出すときに通常料金へ掛けて上乗せする割合（1.0 = 合計 2 倍）。固定分と合算。",
    isPublic: true,
  },
  lora_priority_parallel_surcharge: {
    label: "LoRA 並列実行 固定追加料金",
    category: "feature_credits",
    unit: "C",
    description: "学習中にもう 1 本出すときに 1 ジョブへ一律で足す固定分。率と合算。",
    isPublic: true,
  },
  upscale_priority_parallel_rate: {
    label: "超解像 並列実行 上乗せ率",
    category: "feature_credits",
    unit: "×",
    description: "並列実行時に通常料金へ掛けて上乗せする割合（1.0 = 通常料金と同額を追加 = 合計 2 倍）。固定分と合算。",
    isPublic: true,
  },
  upscale_priority_parallel_surcharge: {
    label: "超解像 並列実行 固定追加料金",
    category: "feature_credits",
    unit: "C",
    description: "並列実行時に 1 ジョブへ一律で足す固定分（コールドスタート分）。率と合算。",
    isPublic: true,
  },
  upscale_mult_power: {
    label: "超解像 パワーティア係数（廃止・未使用）",
    category: "feature_credits",
    unit: "×",
    description: "（廃止）8K も倍率モードも純 MP 課金。この値は使われない。",
    isPublic: false,
  },
  upscale_cascade_mult_2stage: {
    label: "超解像 カスケード係数（2段）",
    category: "feature_credits",
    unit: "×",
    description: "×4 モード（×2→×4 の2段カスケード）に乗せる追加係数。",
    isPublic: true,
  },
  upscale_cascade_mult_3stage: {
    label: "超解像 カスケード係数（3段）",
    category: "feature_credits",
    unit: "×",
    description: "×8 モード（×2→×4→×8 の3段カスケード）に乗せる追加係数。",
    isPublic: true,
  },
  upscale_video_base_credits: {
    label: "動画超解像（固定費・HD基準）",
    category: "feature_credits",
    unit: "C",
    description: "モデルロード等の固定オーバーヘッド分（HD基準、他プリセットはmult_res_2k/4kが乗る）",
    isPublic: true,
  },
  upscale_video_per_frame: {
    label: "動画超解像（1フレームあたり・限界費用分）",
    category: "feature_credits",
    unit: "C/frame",
    description: "出力フレーム数あたりの追加消費クレジット（固定費に対するわずかな上乗せ、× モデル係数）",
    isPublic: true,
  },
  upscale_video_min_credits: {
    label: "動画超解像 最低クレジット",
    category: "feature_credits",
    unit: "C",
    description: "1本あたりの消費クレジット下限（コールドスタート償却）",
    isPublic: true,
  },
  upscale_video_mult_res_2k: {
    label: "動画超解像 2Kプリセット係数",
    category: "feature_credits",
    unit: "×",
    description: "2Kプリセット選択時にper_frameへ掛ける係数（HD=1.0基準、GPU単価差込み実測）",
    isPublic: true,
  },
  upscale_video_mult_res_4k: {
    label: "動画超解像 4Kプリセット係数",
    category: "feature_credits",
    unit: "×",
    description: "4Kプリセット選択時にper_frameへ掛ける係数（HD=1.0基準、GPU単価差込み実測）",
    isPublic: true,
  },
  lora_credits_per_gpu_second: {
    label: "LoRA クレジット単価（ai-toolkit）",
    category: "lora_formula",
    unit: "C/GPU秒",
    description:
      "推定GPU秒に掛けて消費クレジットを出す単価。ai-toolkit ワーカーで回る全 arch（SDXL以外）。",
    isPublic: true,
  },
  lora_credits_per_gpu_second_sdxl: {
    label: "LoRA クレジット単価（sd-scripts / SDXL）",
    category: "lora_formula",
    unit: "C/GPU秒",
    description: "同上。SDXL系（illustrious / juggernaut）は sd-scripts ワーカーで回るため別単価。",
    isPublic: true,
  },
  lora_prep_load_s: {
    label: "LoRA 準備時間（固定分・ai-toolkit）",
    category: "lora_formula",
    unit: "s",
    description:
      "コンテナ起動・モデルロード等、枚数にも step 数にも依らない固定オーバーヘッド。2026-10-04 の本番実測（minimax）で約 116 秒 → 200。",
    isPublic: true,
  },
  lora_prep_dequant_s: {
    label: "LoRA 準備時間（逆量子化ぶん）",
    category: "lora_formula",
    unit: "s",
    description:
      "量子化配布された重みをロード時に full precision へ戻すコスト。2026-10-04 から minimax も bf16 を直接読むので 0（逆量子化なし）。",
    isPublic: true,
  },
  lora_prep_load_s_sdxl: {
    label: "LoRA 準備時間（固定分・sd-scripts / SDXL）",
    category: "lora_formula",
    unit: "s",
    description: "SDXL系（sd-scripts ワーカー）の固定オーバーヘッド。2026-09-20 実測。",
    isPublic: true,
  },
  lora_prep_per_image_s: {
    label: "LoRA 準備時間（1枚あたり）",
    category: "lora_formula",
    unit: "s/枚",
    description: "latent キャッシュのうちデータセット枚数に比例する分（限界費用）",
    isPublic: true,
  },
  lora_res_scale_exponent: {
    label: "LoRA 解像度スケール指数",
    category: "lora_formula",
    unit: "×",
    description: "s/it = 基準値 × (解像度²/1024²)^これ。1.0 で画素数に正比例。",
    isPublic: true,
  },
  lora_batch_marginal_ratio: {
    label: "LoRA 実効バッチの限界比率",
    category: "lora_formula",
    unit: "×",
    description:
      "1ステップのうち実効バッチに比例する割合。1.0で正比例（旧挙動）、0でバッチを上げても所要秒が変わらない。",
    isPublic: true,
  },
  lora_spi_baseline_default: {
    label: "LoRA 未知 arch の s/it",
    category: "lora_formula",
    unit: "s/it",
    description: "loraRuntime.ts の arch 別実測テーブルに無いモデルの 1 イテレーション所要秒",
    isPublic: true,
  },
  lora_per_step: {
    label: "LoRA 基本単価（廃止・未使用）",
    category: "lora_formula",
    unit: "C/step",
    description: "（廃止）推定GPU秒ベースへ移行。loraRuntime.ts 参照。",
    isPublic: false,
  },
  lora_mult_model_heavy: {
    label: "LoRA モデル係数（廃止・未使用）",
    category: "lora_formula",
    unit: "×",
    description: "（廃止）arch 別の実測 s/it テーブル（loraRuntime.ts）に置き換え。",
    isPublic: false,
  },
  lora_mult_res_1024: {
    label: "LoRA 解像度係数 ≥1024px（廃止・未使用）",
    category: "lora_formula",
    unit: "×",
    description: "（廃止）lora_res_scale_exponent による連続式に置き換え。",
    isPublic: false,
  },
  lora_mult_res_1280: {
    label: "LoRA 解像度係数 ≥1280px（廃止・未使用）",
    category: "lora_formula",
    unit: "×",
    description: "（廃止）lora_res_scale_exponent による連続式に置き換え。",
    isPublic: false,
  },
  lora_mult_batch_2: {
    label: "LoRA バッチ係数 ≥2（廃止・未使用）",
    category: "lora_formula",
    unit: "×",
    description: "（廃止）実効バッチは所要秒に正比例するものとして直接掛ける。",
    isPublic: false,
  },
  lora_mult_batch_4: {
    label: "LoRA バッチ係数 ≥4（廃止・未使用）",
    category: "lora_formula",
    unit: "×",
    description: "（廃止）実効バッチは所要秒に正比例するものとして直接掛ける。",
    isPublic: false,
  },
  lora_mult_rank_64: {
    label: "LoRA Rank 係数（廃止・未使用）",
    category: "lora_formula",
    unit: "×",
    description:
      "（廃止）LoRA アダプタは基盤モデルに対して十分小さく、rank は所要秒をほとんど動かさないため課金要素から外した。",
    isPublic: false,
  },
  angle_time_per_credit_s: {
    label: "Angle 損切り：1C あたり猶予秒",
    category: "cost_guard",
    unit: "s/C",
    description: "max_allowed_time = 消費C × これ + コールドスタート猶予",
    isPublic: false,
  },
  angle_cold_start_grace_s: {
    label: "Angle 損切り：コールドスタート猶予",
    category: "cost_guard",
    unit: "s",
    description: "コンテナ起動 + モデルロード + 初回 forward warmup の固定猶予",
    isPublic: false,
  },
  upscale_time_per_credit_s: {
    label: "超解像 損切り：1C あたり猶予秒",
    category: "cost_guard",
    unit: "s/C",
    description: "max_allowed_time = 消費C × これ + コールドスタート猶予",
    isPublic: false,
  },
  upscale_cold_start_grace_s: {
    label: "超解像 損切り：コールドスタート猶予",
    category: "cost_guard",
    unit: "s",
    description: "ComfyUI 起動 + SeedVR2 重みロード + 初回 forward の固定猶予",
    isPublic: false,
  },
  upscale_batch_max_seconds: {
    label: "超解像 バッチ：合計処理秒数の上限",
    category: "cost_guard",
    unit: "s",
    description: "1バッチの推定合計処理秒数がこれを超えたら受け付けない。",
    isPublic: false,
  },
  upscale_video_time_per_credit_s: {
    label: "動画超解像 損切り：1C あたり猶予秒",
    category: "cost_guard",
    unit: "s/C",
    description: "max_allowed_time = 消費C × これ + コールドスタート猶予",
    isPublic: false,
  },
  upscale_video_cold_start_grace_s: {
    label: "動画超解像 損切り：コールドスタート猶予",
    category: "cost_guard",
    unit: "s",
    description: "ComfyUI起動+SeedVR2重みロード+VHSノード初回実行の固定猶予",
    isPublic: false,
  },
  lora_cost_guard_multiplier: {
    label: "LoRA 損切り：余裕倍率",
    category: "cost_guard",
    unit: "×",
    description: "クレジット按分秒 × これ = 予測壁時計の停止閾値。1.0 で厳格な損益分岐。",
    isPublic: false,
  },
  lora_margin_target: {
    label: "LoRA 損切り：粗利ターゲット",
    category: "cost_guard",
    unit: "率",
    description: "0.7 = GPU 原価を売上の 70% までに抑える（粗利 30%）",
    isPublic: false,
  },
  lora_floor_prep_s: {
    label: "LoRA 損切り：prep 下駄秒（廃止・未使用）",
    category: "cost_guard",
    unit: "s",
    description: "（廃止）prep は lora_prep_* knob で明示的に見積もるようになった。",
    isPublic: false,
  },
  lora_safety_limit_s: {
    label: "LoRA 損切り：0C ジョブ上限",
    category: "cost_guard",
    unit: "s",
    description: "クレジット 0（生 YAML パース不能）ジョブの絶対上限秒",
    isPublic: false,
  },
  alert_low_margin_percent: {
    label: "粗利アラート閾値",
    category: "cost_guard",
    unit: "%",
    description: "この粗利率を下回るジョブを「低粗利」として実稼働ログのアラートに表示する",
    isPublic: false,
  },
  credit_to_jpy: {
    label: "クレジット売上単価",
    category: "rates",
    unit: "円/C",
    description: "最安サブスク単価。損益計算・Cost Simulator の売上換算に使用。",
    isPublic: false,
  },
  gpu_usd_per_hour_b300: {
    label: "GPU 時給（B300, USD）",
    category: "rates",
    unit: "$/h",
    description: "LoRA 損切りのクレジット按分秒の分母。実稼働ログの原価計算にも使用。",
    isPublic: false,
  },
  gpu_usd_per_hour_b200: {
    label: "GPU 時給（B200, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_h200: {
    label: "GPU 時給（H200, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_h100: {
    label: "GPU 時給（H100, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_rtx_pro_6000: {
    label: "GPU 時給（RTX PRO 6000, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_a100_80gb: {
    label: "GPU 時給（A100 80GB, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_a100_40gb: {
    label: "GPU 時給（A100 40GB, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_l40s: {
    label: "GPU 時給（L40S, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_a10: {
    label: "GPU 時給（A10, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_l4: {
    label: "GPU 時給（L4, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  gpu_usd_per_hour_t4: {
    label: "GPU 時給（T4, USD）",
    category: "rates",
    unit: "$/h",
    description: "実稼働ログの原価計算用",
    isPublic: false,
  },
  cpu_usd_per_core_hour: {
    label: "CPU 1 コア時給（USD）",
    category: "rates",
    unit: "$/core-h",
    description: "実稼働ログの原価計算用（gpu_tier が cpu<コア数> の行）",
    isPublic: false,
  },
  usd_jpy_rate: {
    label: "為替レート（USD/JPY）",
    category: "rates",
    unit: "円/$",
    description: "Cost Simulator の Modal 原価（USD 建て）換算レートの既定値",
    isPublic: false,
  },
};

export const KNOB_META = Object.fromEntries(
  (Object.keys(KNOB_TEXT) as KnobKey[]).map((k) => [k, { value: DEFAULT_KNOBS[k], ...KNOB_TEXT[k] }]),
) as Record<KnobKey, KnobMeta>;

/** Exposed to the browser via GET /api/studio/pricing. */
export const PUBLIC_KNOB_KEYS: KnobKey[] = (Object.keys(KNOB_TEXT) as KnobKey[]).filter((k) => KNOB_TEXT[k].isPublic);
